# Generated by Django 3.2.16 on 2022-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, verbose_name='surname')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('about', models.TextField(verbose_name='about')),
                ('login', models.CharField(max_length=20, verbose_name='login')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
            ],
        ),
    ]
